<a href="https://colab.research.google.com/github/junghunam/Python-lets-goooooo/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%84%B1%EC%9E%A5%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = ['No', 'pain', 'No', 'gain']
' '.join(a)


'No pain No gain'

조건문

In [ ]:
65 > 90

False

In [ ]:
if 95 > 90:
    print('95 > 90')

95 > 90


In [ ]:
if 65 > 90:
    print('65 > 90')

In [ ]:
score = 80
if score >=90:
  print('합격입니다')
else:
  print('축하합니다')

축하합니다


In [ ]:
money = 22500
if money < 5000:
    print('빵을 먹는다.') 
elif money < 15000: # 5000 <= money <15000
    print('돈가스를 먹는다.')
elif money < 20000: # 5000 <= money <15000
    print('치킨을 먹는다.')
elif money < 30000: # 5000 <= money <15000
    print('초밥을 먹는다.')
else: # money > 15000
    print('초밥과 치킨을 먹는다.')

초밥을 먹는다.


In [ ]:
money = 3000
if money < 5000:
  pass 
elif money < 15000:
  print('돈가스를 먹는다.')
else:
  print('치킨을 먹는다.')

In [ ]:
hungry = True
money = 1000
if hungry:
  if money < 5000:
    print('김밥을 먹는다.')
  else:
    print('김치볶음밥을 먹는다.')
else:
  if money > 3000:
    print('캔맥주를 산다')
  else :
    print('집에 가야지 뭐, 탄산수나 살까')

김밥을 먹는다.


In [ ]:
for i in range(2,10):
    for j in range(1,10):
        print(i*j, end=' ')

    print('')

2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 
9 18 27 36 45 54 63 72 81 


In [ ]:
print (1, end='')
print (2, end=' ')

print (3)
print (4)

12 3
4


함수

In [ ]:
A = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
total = 0

for score in A:
    total = total + score  # 리스트 A의 각 요소를 합계에 더합니다.
a = total / 10  # 평균을 계산합니다.
print(a)

79.0


In [ ]:
def numbers_avg(*args):
    result = 0
    for i in args:
        result += i
    return result / len(args)

In [ ]:
numbers_avg(1,2,3,4,5,6,7,8,9,10)

5.5

In [ ]:
def is_odd(number):
    if number%2==0:
        return True
    else:
        return False

In [ ]:
is_odd(3)

False

심화

In [ ]:
people = ['김씨', '최씨', '이씨']
i = 1
for j in people:
    print('번호:{},     성:{}'.format(i, j))
    i = i + 1

번호:1,     성:김씨
번호:2,     성:최씨
번호:3,     성:이씨


In [ ]:
people = ['김씨', '최씨', '이씨']
for x, y in enumerate(people):
    print(x+1,y)

1 김씨
2 최씨
3 이씨


In [ ]:
people = ['김씨', '최씨', '이씨']
for number, name in enumerate(people):
    print('번호: {}, 성: {}'.format(number+1, name))

번호: 1, 성: 김씨
번호: 2, 성: 최씨
번호: 3, 성: 이씨


In [ ]:
list(zip([1, 2, 3], [4, 5,6],[7,8,9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [ ]:
a = [1.1, 2.3, 3.5, 4.1]
map(str,a)
list(map(str,a))

['1.1', '2.3', '3.5', '4.1']

In [ ]:
list(map(lambda a:a*2, [1,2,3,4]))


[2, 4, 6, 8]

로또 자동 번호 추출
(숫자 1~45 중 랜덤 6개 추출)

self 풀이

In [82]:
import random as rd

In [83]:
rd.randrange(1,7)

2

In [84]:
lotto = [0,0,0,0,0,0]
lotto

[0, 0, 0, 0, 0, 0]

In [56]:
lotto[1] = 1
lotto

[0, 1, 0, 0, 0, 0]

In [87]:
lotto[0] = rd.randrange(1,46)
lotto[1] = rd.randrange(1,46)
lotto[2] = rd.randrange(1,46)
lotto[3] = rd.randrange(1,46)
lotto[4] = rd.randrange(1,46)
lotto[5] = rd.randrange(1,46)
lotto.sort()
lotto

[1, 3, 8, 11, 12, 12]

Cgpt

In [70]:
import random as rd

lotto = []
while len(lotto) < 6:
    number = rd.randrange(1, 46)
    if number not in lotto:
        lotto.append(number)
lotto

[5, 33, 12, 16, 29, 20]

강사 풀이

In [98]:
lotto = [0,0,0,0,0,0]
lotto[0] = rd.randrange(1,46)
lotto[1] = lotto[0]
lotto[2] = lotto[0]
lotto[3] = lotto[0]
lotto[4] = lotto[0]
lotto[5] = lotto[0]

while lotto[1] == lotto[0]: # while 만족하지 않을 때까지 실행
    lotto[1] = rd.randrange(1, 46)

while lotto[2] == lotto[0] or lotto[2] == lotto[1]:
    lotto[2] = rd.randrange(1, 46)

while lotto[3] == lotto[0] or lotto[3] == lotto[1] or lotto[3] == lotto[2]:
    lotto[3] = rd.randrange(1, 46)

while lotto[4] == lotto[0] or lotto[4] == lotto[1] or lotto[4] == lotto[2] or lotto[4] == lotto[3]:
    lotto[4] = rd.randrange(1, 46)

while lotto[5] == lotto[0] or lotto[5] == lotto[1] or lotto[5] == lotto[2] or lotto[5] == lotto[3] or lotto[5] == lotto[4]:
    lotto[5] = rd.randrange(1, 46)
    
lotto.sort()
print(lotto)

[17, 20, 22, 25, 29, 32]


n번 로또 번호 생성

In [102]:
int(input('Lotto 게임 수를 입력하시오. : '))

Lotto 게임 수를 입력하시오. : 2


2

In [110]:
num = int(input('Lotto 게임 수를 입력하시오. : '))
# num = 2
print('Lotto 당첨 번호입니다.')
print('='*25)

# 입력한 게임 수 만큼 반복

for x in range(1, num+1):# 1부터 num까지 수행
    lotto = [0, 0, 0, 0, 0, 0]
    lotto[0] = rd.randrange(1, 46)
    lotto[1] = lotto[0]
    lotto[2] = lotto[0]
    lotto[3] = lotto[0]
    lotto[4] = lotto[0]
    lotto[5] = lotto[0]

# # 중복된 수 발생 방지
    while lotto[1] == lotto[0]: # while 만족하지 않을 때까지 실행
        lotto[1] = rd.randrange(1, 46)
    while lotto[2] == lotto[0] or lotto[2] == lotto[1]:
        lotto[2] = rd.randrange(1, 46)
    while lotto[3] == lotto[0] or lotto[3] == lotto[1] or lotto[3] == lotto[2]:
        lotto[3] = rd.randrange(1, 46)
    while lotto[4] == lotto[0] or lotto[4] == lotto[1] or lotto[4] == lotto[2] or lotto[4] == lotto[3]:
        lotto[4] = rd.randrange(1, 46)
    while lotto[5] == lotto[0] or lotto[5] == lotto[1] or lotto[5] == lotto[2] or lotto[5] == lotto[3] or lotto[5] == lotto[4]:
        lotto[5] = rd.randrange(1, 46)
    lotto.sort()
# 결과 출력
    print(lotto)

Lotto 게임 수를 입력하시오. : 5
Lotto 당첨 번호입니다.
[2, 5, 6, 7, 20, 30]
[3, 9, 11, 21, 40, 44]
[1, 9, 27, 29, 36, 42]
[9, 14, 19, 22, 28, 34]
[6, 12, 23, 24, 33, 42]


주민번호 판독 프로그래밍

In [143]:
jb = '9912131411611'
if jb[6:7]:
    print('성별 : 남성')
else:
    print('성별 : 여성')
    
    


성별 : 남성


In [174]:
def check_jumin(jumin):
    # 주민번호 유효성 검사
    if len(jumin) != 13 or not jumin.isdigit():
        return "유효하지 않은 주민번호입니다."

    # 생년월일 추출
    birth_year = int(jumin[0:2])
    birth_month = int(jumin[2:4])
    birth_day = int(jumin[4:6])

    # 성별 추출
    gender = int(jumin[6])
    if gender == 1 or gender == 3 :
        gender = "남성"
    else:
        gender = "여성"

    # 출생지역 추출
    region_code = jumin[7:9]
    region = get_region(region_code)

    # 결과 반환
    result = f"생년월일: {birth_year}년 {birth_month}월 {birth_day}일\n성별: {gender}\n출생지역: {region}"
    return result


def get_region(region_code):
    # 출생지역 코드에 따라 지역명 반환
    # 본 예시에서는 일부 지역만 예시로 나열하였습니다.
    region_dict = {
        "41": "충청남도",
        "42": "충청남도",
        "43": "충청남도",
        "44": "세종특별자치시",
        "45": "충청남도",
        "46": "충청남도",
        "47": "충청남도",
    }

    region = region_dict.get(region_code, "알 수 없음")
    return region


# 주민번호 입력 받기
jumin_number = input("주민번호를 입력하세요 (13자리): ")

# 주민번호 판독 및 결과 출력
result = check_jumin(jumin_number)
print(result)


주민번호를 입력하세요 (13자리): 9912131411611
생년월일: 99년 12월 13일
성별: 남성
출생지역: 충청남도


numpy

In [178]:
import numpy as np

In [179]:
data1=[1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [180]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [181]:
arr1.ndim

1

In [182]:
arr1.shape

(5,)

In [183]:
arr1.dtype

dtype('int64')

In [190]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [192]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [201]:
np.random.randint(1,46,size=6)

array([15, 32, 23,  1, 44, 45])

In [205]:
np.random.rand(3,2)

array([[0.57513177, 0.43769339],
       [0.13307041, 0.41901498],
       [0.13533557, 0.59636274]])

In [213]:
np.random.seed(10)
np.random.rand(3,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665]])

In [215]:
np.random.seed(10)
data=np.random.rand(3,2)
data            

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665]])

In [217]:
np.random.shuffle(data)
data

array([[0.63364823, 0.74880388],
       [0.77132064, 0.02075195],
       [0.49850701, 0.22479665]])

In [220]:
data = ['apple', 'banana', 'strewberry']
np.random.choice(data)

'apple'

In [222]:
np.random.choice(data,2)

array(['apple', 'apple'], dtype='<U10')

In [231]:
np.random.choice(data,2,p=[0.1,0.5,0.4])

array(['strewberry', 'strewberry'], dtype='<U10')

In [234]:
data = ['apple', 'apple', 'strewberry']
np.unique(data)

array(['apple', 'strewberry'], dtype='<U10')

In [236]:
set(data)

{'apple', 'strewberry'}

1-100사이의 정수 중 랜덤하게 한개의 숫자 추출 and 두개의 숫자 추출

In [246]:
np.random.randint(1,101)

26

In [247]:
np.random.randint(1,101,size=2)

array([20, 49])