<a href="https://colab.research.google.com/github/junghunam/Python-lets-goooooo/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%84%B1%EC%9E%A5%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = ['No', 'pain', 'No', 'gain']
' '.join(a)


'No pain No gain'

조건문

In [ ]:
65 > 90

False

In [ ]:
if 95 > 90:
    print('95 > 90')

95 > 90


In [ ]:
if 65 > 90:
    print('65 > 90')

In [ ]:
score = 80
if score >=90:
  print('합격입니다')
else:
  print('축하합니다')

축하합니다


In [ ]:
money = 22500
if money < 5000:
    print('빵을 먹는다.') 
elif money < 15000: # 5000 <= money <15000
    print('돈가스를 먹는다.')
elif money < 20000: # 5000 <= money <15000
    print('치킨을 먹는다.')
elif money < 30000: # 5000 <= money <15000
    print('초밥을 먹는다.')
else: # money > 15000
    print('초밥과 치킨을 먹는다.')

초밥을 먹는다.


In [ ]:
money = 3000
if money < 5000:
  pass 
elif money < 15000:
  print('돈가스를 먹는다.')
else:
  print('치킨을 먹는다.')

In [ ]:
hungry = True
money = 1000
if hungry:
  if money < 5000:
    print('김밥을 먹는다.')
  else:
    print('김치볶음밥을 먹는다.')
else:
  if money > 3000:
    print('캔맥주를 산다')
  else :
    print('집에 가야지 뭐, 탄산수나 살까')

김밥을 먹는다.


In [ ]:
for i in range(2,10):
    for j in range(1,10):
        print(i*j, end=' ')

    print('')

2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 
9 18 27 36 45 54 63 72 81 


In [ ]:
print (1, end='')
print (2, end=' ')

print (3)
print (4)

12 3
4


함수

In [ ]:
A = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
total = 0

for score in A:
    total = total + score  # 리스트 A의 각 요소를 합계에 더합니다.
a = total / 10  # 평균을 계산합니다.
print(a)

79.0


In [ ]:
def numbers_avg(*args):
    result = 0
    for i in args:
        result += i
    return result / len(args)

In [ ]:
numbers_avg(1,2,3,4,5,6,7,8,9,10)

5.5

In [ ]:
def is_odd(number):
    if number%2==0:
        return True
    else:
        return False

In [ ]:
is_odd(3)

False

심화

In [ ]:
people = ['김씨', '최씨', '이씨']
i = 1
for j in people:
    print('번호:{},     성:{}'.format(i, j))
    i = i + 1

번호:1,     성:김씨
번호:2,     성:최씨
번호:3,     성:이씨


In [ ]:
people = ['김씨', '최씨', '이씨']
for x, y in enumerate(people):
    print(x+1,y)

1 김씨
2 최씨
3 이씨


In [ ]:
people = ['김씨', '최씨', '이씨']
for number, name in enumerate(people):
    print('번호: {}, 성: {}'.format(number+1, name))

번호: 1, 성: 김씨
번호: 2, 성: 최씨
번호: 3, 성: 이씨


In [ ]:
list(zip([1, 2, 3], [4, 5,6],[7,8,9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [ ]:
a = [1.1, 2.3, 3.5, 4.1]
map(str,a)
list(map(str,a))

['1.1', '2.3', '3.5', '4.1']

In [ ]:
list(map(lambda a:a*2, [1,2,3,4]))


[2, 4, 6, 8]

로또 자동 번호 추출
(숫자 1~45 중 랜덤 6개 추출)

self 풀이

In [ ]:
import random as rd

In [ ]:
rd.randrange(1,7)

2

In [ ]:
lotto = [0,0,0,0,0,0]
lotto

[0, 0, 0, 0, 0, 0]

In [ ]:
lotto[1] = 1
lotto

[0, 1, 0, 0, 0, 0]

In [ ]:
lotto[0] = rd.randrange(1,46)
lotto[1] = rd.randrange(1,46)
lotto[2] = rd.randrange(1,46)
lotto[3] = rd.randrange(1,46)
lotto[4] = rd.randrange(1,46)
lotto[5] = rd.randrange(1,46)
lotto.sort()
lotto

[1, 3, 8, 11, 12, 12]

Cgpt

In [ ]:
import random as rd

lotto = []
while len(lotto) < 6:
    number = rd.randrange(1, 46)
    if number not in lotto:
        lotto.append(number)
lotto

[5, 33, 12, 16, 29, 20]

강사 풀이

In [ ]:
lotto = [0,0,0,0,0,0]
lotto[0] = rd.randrange(1,46)
lotto[1] = lotto[0]
lotto[2] = lotto[0]
lotto[3] = lotto[0]
lotto[4] = lotto[0]
lotto[5] = lotto[0]

while lotto[1] == lotto[0]: # while 만족하지 않을 때까지 실행
    lotto[1] = rd.randrange(1, 46)

while lotto[2] == lotto[0] or lotto[2] == lotto[1]:
    lotto[2] = rd.randrange(1, 46)

while lotto[3] == lotto[0] or lotto[3] == lotto[1] or lotto[3] == lotto[2]:
    lotto[3] = rd.randrange(1, 46)

while lotto[4] == lotto[0] or lotto[4] == lotto[1] or lotto[4] == lotto[2] or lotto[4] == lotto[3]:
    lotto[4] = rd.randrange(1, 46)

while lotto[5] == lotto[0] or lotto[5] == lotto[1] or lotto[5] == lotto[2] or lotto[5] == lotto[3] or lotto[5] == lotto[4]:
    lotto[5] = rd.randrange(1, 46)
    
lotto.sort()
print(lotto)

[17, 20, 22, 25, 29, 32]


n번 로또 번호 생성

In [ ]:
int(input('Lotto 게임 수를 입력하시오. : '))

Lotto 게임 수를 입력하시오. : 2


2

In [ ]:
num = int(input('Lotto 게임 수를 입력하시오. : '))
# num = 2
print('Lotto 당첨 번호입니다.')
print('='*25)

# 입력한 게임 수 만큼 반복

for x in range(1, num+1):# 1부터 num까지 수행
    lotto = [0, 0, 0, 0, 0, 0]
    lotto[0] = rd.randrange(1, 46)
    lotto[1] = lotto[0]
    lotto[2] = lotto[0]
    lotto[3] = lotto[0]
    lotto[4] = lotto[0]
    lotto[5] = lotto[0]

# # 중복된 수 발생 방지
    while lotto[1] == lotto[0]: # while 만족하지 않을 때까지 실행
        lotto[1] = rd.randrange(1, 46)
    while lotto[2] == lotto[0] or lotto[2] == lotto[1]:
        lotto[2] = rd.randrange(1, 46)
    while lotto[3] == lotto[0] or lotto[3] == lotto[1] or lotto[3] == lotto[2]:
        lotto[3] = rd.randrange(1, 46)
    while lotto[4] == lotto[0] or lotto[4] == lotto[1] or lotto[4] == lotto[2] or lotto[4] == lotto[3]:
        lotto[4] = rd.randrange(1, 46)
    while lotto[5] == lotto[0] or lotto[5] == lotto[1] or lotto[5] == lotto[2] or lotto[5] == lotto[3] or lotto[5] == lotto[4]:
        lotto[5] = rd.randrange(1, 46)
    lotto.sort()
# 결과 출력
    print(lotto)

Lotto 게임 수를 입력하시오. : 5
Lotto 당첨 번호입니다.
[2, 5, 6, 7, 20, 30]
[3, 9, 11, 21, 40, 44]
[1, 9, 27, 29, 36, 42]
[9, 14, 19, 22, 28, 34]
[6, 12, 23, 24, 33, 42]


주민번호 판독 프로그래밍

In [ ]:
jb = '9912131411611'
if jb[6:7]:
    print('성별 : 남성')
else:
    print('성별 : 여성')
    
    


성별 : 남성


In [ ]:
def check_jumin(jumin):
    # 주민번호 유효성 검사
    if len(jumin) != 13 or not jumin.isdigit():
        return "유효하지 않은 주민번호입니다."

    # 생년월일 추출
    birth_year = int(jumin[0:2])
    birth_month = int(jumin[2:4])
    birth_day = int(jumin[4:6])

    # 성별 추출
    gender = int(jumin[6])
    if gender == 1 or gender == 3 :
        gender = "남성"
    else:
        gender = "여성"

    # 출생지역 추출
    region_code = jumin[7:9]
    region = get_region(region_code)

    # 결과 반환
    result = f"생년월일: {birth_year}년 {birth_month}월 {birth_day}일\n성별: {gender}\n출생지역: {region}"
    return result


def get_region(region_code):
    # 출생지역 코드에 따라 지역명 반환
    # 본 예시에서는 일부 지역만 예시로 나열하였습니다.
    region_dict = {
        "41": "충청남도",
        "42": "충청남도",
        "43": "충청남도",
        "44": "세종특별자치시",
        "45": "충청남도",
        "46": "충청남도",
        "47": "충청남도",
    }

    region = region_dict.get(region_code, "알 수 없음")
    return region


# 주민번호 입력 받기
jumin_number = input("주민번호를 입력하세요 (13자리): ")

# 주민번호 판독 및 결과 출력
result = check_jumin(jumin_number)
print(result)


주민번호를 입력하세요 (13자리): 9912131411611
생년월일: 99년 12월 13일
성별: 남성
출생지역: 충청남도


numpy

In [ ]:
import numpy as np

In [ ]:
data1=[1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [ ]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.ndim

1

In [ ]:
arr1.shape

(5,)

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
np.random.randint(1,46,size=6)

array([15, 32, 23,  1, 44, 45])

In [ ]:
np.random.rand(3,2)

array([[0.57513177, 0.43769339],
       [0.13307041, 0.41901498],
       [0.13533557, 0.59636274]])

In [ ]:
np.random.seed(10)
np.random.rand(3,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665]])

In [ ]:
np.random.seed(10)
data=np.random.rand(3,2)
data            

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665]])

In [ ]:
np.random.shuffle(data)
data

array([[0.63364823, 0.74880388],
       [0.77132064, 0.02075195],
       [0.49850701, 0.22479665]])

In [ ]:
data = ['apple', 'banana', 'strewberry']
np.random.choice(data)

'apple'

In [ ]:
np.random.choice(data,2)

array(['apple', 'apple'], dtype='<U10')

In [ ]:
np.random.choice(data,2,p=[0.1,0.5,0.4])

array(['strewberry', 'strewberry'], dtype='<U10')

In [ ]:
data = ['apple', 'apple', 'strewberry']
np.unique(data)

array(['apple', 'strewberry'], dtype='<U10')

In [ ]:
set(data)

{'apple', 'strewberry'}

1-100사이의 정수 중 랜덤하게 한개의 숫자 추출 and 두개의 숫자 추출

In [ ]:
np.random.randint(1,101)

26

In [ ]:
np.random.randint(1,101,size=2)

array([20, 49])

pandas

In [ ]:
import pandas as pd

In [ ]:
x = [1,-5,7,4,8]

리스트로 만들기

In [ ]:
pd.Series(x)

0    1
1   -5
2    7
3    4
4    8
dtype: int64

In [ ]:
x = [1,'A','b',4,8]
x

[1, 'A', 'b', 4, 8]

In [ ]:
dt1 = pd.Series(x)

In [ ]:
dt1.values

array([1, 'A', 'b', 4, 8], dtype=object)

In [ ]:
dt1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
dt2 = pd.Series(data=[1,-5,7,4,8], index=['d','b','e','a','c'])
dt2

d    1
b   -5
e    7
a    4
c    8
dtype: int64

In [ ]:
dt2.index

Index(['d', 'b', 'e', 'a', 'c'], dtype='object')

튜플로 만들기

In [ ]:
data = ('홍길동','1995-02-08','남',True) #튜플
dt3 = pd.Series(data, ['이름','생년월일','성별','수강여부'])
dt3

이름             홍길동
생년월일    1995-02-08
성별               남
수강여부          True
dtype: object

딕셔너리로 만들기`

In [ ]:
data = {'d': 1, 'b': -5, 'e': 7, 'a': 4, 'c': 8} #딕셔너리
dt3 = pd.Series(data)
dt3

d    1
b   -5
e    7
a    4
c    8
dtype: int64

In [ ]:
dt3.name = 'series이름' # series데이터.name : 시리즈이름
dt3.index.name = 'index이름'# series데이터.index.name : 인덱스이름

In [ ]:
dt3

KIM     1
LEE    -5
CHOI    7
PARK    4
AHN     8
Name: series이름, dtype: int64

In [ ]:
dt3.index = ['KIM', 'LEE', 'CHOI', 'PARK','AHN']

In [ ]:
dt3[1]

-5

In [ ]:
dt3['LEE']

-5

자료 구조: DataFrame

In [ ]:
import pandas as pd

리스트로 만들기

In [ ]:
df1 = pd.DataFrame([['a',10,110],['b',9,90],['c',10,80],
['a',20,150],['c',7,90],['d',8,79],
['e',10,96],['a',6,120]])

In [ ]:
df1

0   1    2
0  a  10  110
1  b   9   90
2  c  10   80
3  a  20  150
4  c   7   90
5  d   8   79
6  e  10   96
7  a   6  120

In [ ]:
df1 = pd.DataFrame(data = [['a',10,110],['b',9,90],['c',10,80],
['a',20,150],['c',7,90],['d',8,79],
['e',10,96],['a',6,120]],
columns = ['val0', 'val1', 'val2'],
index =['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'])
df1

val0  val1  val2
x1    a    10   110
x2    b     9    90
x3    c    10    80
x4    a    20   150
x5    c     7    90
x6    d     8    79
x7    e    10    96
x8    a     6   120

딕셔너리로 만들기

In [ ]:
df2 = pd.DataFrame(data = { 'val0' : ['a','b','c','a','c','d','e','a'],
                            'val1' : [10, 9, 10, 20, 7, 8, 10, 6],
                            'val2' : [110, 90, 80, 150, 90, 79, 96, 120]},
                            columns = ['val0', 'val1', 'val2'],
                            index = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'])
df2

val0  val1  val2
x1    a    10   110
x2    b     9    90
x3    c    10    80
x4    a    20   150
x5    c     7    90
x6    d     8    79
x7    e    10    96
x8    a     6   120

In [ ]:
value0 = ['a','b','c','a','c','d','e','a']
value1 = [10, 9, 10, 20, 7, 8, 10, 6]
value2 = [110, 90, 80, 150, 90, 79, 96, 120]
df2 = pd.DataFrame({'val0' : value0, 'val1': value1, 'val2': value2})
df2


val0  val1  val2
0    a    10   110
1    b     9    90
2    c    10    80
3    a    20   150
4    c     7    90
5    d     8    79
6    e    10    96
7    a     6   120

시리즈 to 데이터프레임

In [ ]:
import numpy as np

In [ ]:
np.random.randint(0,100)

7

In [ ]:
dt4 = pd.Series(data=np.random.randint(0,100,size=10),
index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
dt4

a    66
b    27
c    92
d    17
e    85
f    72
g     7
h    49
i    29
j    11
dtype: int64

In [ ]:
pd.DataFrame(dt4)

0
a  66
b  27
c  92
d  17
e  85
f  72
g   7
h  49
i  29
j  11

In [ ]:
dt1 = pd.Series(np.random.randint(0,100,size=10),
index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
dt2 = pd.Series(np.random.randint(40,100,size=10),
index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
dt3 = pd.Series(np.random.randint(80,100,size=10),
index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

In [ ]:
df_total = pd.concat([dt1, dt2, dt3], axis=1) # axis =1 열 / axis =0 행 
df_total

0   1   2
a  21  93  97
b  46  62  99
c  35  43  82
d  28  45  89
e  98  41  99
f  92  77  98
g  69  61  89
h  46  79  98
i  89  69  95
j  97  54  91

연습문제

In [ ]:
df0 = pd.DataFrame(data= [['201901','원빈',70,'C'],['201902','김우빈',90,'A'],['202001','서강준',80,'B'],
                    ['201504','장나라',100,'A+'],['201402','김사랑',75,'C+'],['201809','최준',79,'C+']],
                    columns = ['학번', '이름', '성적','학점'], index = ['a','b','c','d','e','f'])
df0

학번   이름   성적  학점
a  201901   원빈   70   C
b  201902  김우빈   90   A
c  202001  서강준   80   B
d  201504  장나라  100  A+
e  201402  김사랑   75  C+
f  201809   최준   79  C+

전처리

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(data = { 'group' : ['A','B','A','A','B','C','C','B'],
                            'score' : [10, 9, 10, 20, 7, 8, 10, 6],
                            'age' : [27, 28, 30, 36, 24, 27, 33, 25]},
                            columns = ['group', 'score', 'age'],
                            index = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'] )
df

group  score  age
x1     A     10   27
x2     B      9   28
x3     A     10   30
x4     A     20   36
x5     B      7   24
x6     C      8   27
x7     C     10   33
x8     B      6   25

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, x1 to x8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   group   8 non-null      object
 1   score   8 non-null      int64 
 2   age     8 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 556.0+ bytes


In [ ]:
df.columns

Index(['group', 'score', 'age'], dtype='object')

특정 열 추출

In [ ]:
df['score']

x1    10
x2     9
x3    10
x4    20
x5     7
x6     8
x7    10
x8     6
Name: score, dtype: int64

특정 행 추출

In [ ]:
df['x1':'x2']

group  score  age
x1     A     10   27
x2     B      9   28

명칭으로 추출 loc



In [ ]:
df.loc['x1','age']

27

In [ ]:
df.loc['x1']

group     A
score    10
age      27
Name: x1, dtype: object

In [ ]:
df.loc[:,'age']

x1    27
x2    28
x3    30
x4    36
x5    24
x6    27
x7    33
x8    25
Name: age, dtype: int64

In [ ]:
df.loc['x1':'x3',['group','age']]

group  age
x1     A   27
x2     B   28
x3     A   30

인덱스번호로 추출 iloc

In [ ]:
df.iloc[:,0]

x1    A
x2    B
x3    A
x4    A
x5    B
x6    C
x7    C
x8    B
Name: group, dtype: object

In [ ]:
df.iloc[0:3,1:3]

score  age
x1     10   27
x2      9   28
x3     10   30

조건선택 T or F

In [ ]:
df['score'] >=10

x1     True
x2    False
x3     True
x4     True
x5    False
x6    False
x7     True
x8    False
Name: score, dtype: bool

In [ ]:
df[df['score'] >=10]

group  score  age
x1     A     10   27
x3     A     10   30
x4     A     20   36
x7     C     10   33

In [ ]:
df.loc[df['score'] >=10]

group  score  age
x1     A     10   27
x3     A     10   30
x4     A     20   36
x7     C     10   33

In [ ]:
df[df['group'] == 'A']

group  score  age
x1     A     10   27
x3     A     10   30
x4     A     20   36

A그룹이 아니고, 30살이 넘는 data 선택하기

In [ ]:
(df['group'] != 'A') & (df['age'] > 30)

x1    False
x2    False
x3    False
x4    False
x5    False
x6    False
x7     True
x8    False
dtype: bool

In [ ]:
df.loc[(df['group'] != 'A') & (df['age'] > 30)]

group  score  age
x7     C     10   33

행열 삭제

In [ ]:
df.drop(columns=['age'])

group  score
x1     A     10
x2     B      9
x3     A     10
x4     A     20
x5     B      7
x6     C      8
x7     C     10
x8     B      6

In [ ]:
df.drop(columns = ['group','age'])

score
x1     10
x2      9
x3     10
x4     20
x5      7
x6      8
x7     10
x8      6

In [ ]:
df.index[0:3]

Index(['x1', 'x2', 'x3'], dtype='object')

In [ ]:
df.drop(df.index[0:3])

group  score  age
x4     A     20   36
x5     B      7   24
x6     C      8   27
x7     C     10   33
x8     B      6   25

행열 추가

In [ ]:
df['new'] = [0,1,0,1,0,1,0,0]
df

group  score  age  new
x1     A     10   27    0
x2     B      9   28    1
x3     A     10   30    0
x4     A     20   36    1
x5     B      7   24    0
x6     C      8   27    1
x7     C     10   33    0
x8     B      6   25    0

In [ ]:
df.loc['x9'] = 'c',14,23,1
df

group  score  age  new
x1     A     10   27    0
x2     B      9   28    1
x3     A     10   30    0
x4     A     20   36    1
x5     B      7   24    0
x6     C      8   27    1
x7     C     10   33    0
x8     B      6   25    0
x9     c     14   23    1

*조건에 따른 결과값 추가

score 가 10 미만이면 'low', 15 이상이면 'high', 나머지는 'medium'

map(함수,데이터) / lamda 

*삼항연산자

true if 조건 else false

In [ ]:
df['new_1'] = df['score'].map(lambda x: 'low' if x<10 else 'high' if x>15 else 'medium')
df

group  score  age  new   new_1
x1     A     10   27    0  medium
x2     B      9   28    1     low
x3     A     10   30    0  medium
x4     A     20   36    1    high
x5     B      7   24    0     low
x6     C      8   27    1     low
x7     C     10   33    0  medium
x8     B      6   25    0     low
x9     c     14   23    1  medium

컬럼별 사칙연산도 가능

In [ ]:
df['new_2'] = df['score'] + df['age']
df

group  score  age  new   new_1  new_2
x1     A     10   27    0  medium     37
x2     B      9   28    1     low     37
x3     A     10   30    0  medium     40
x4     A     20   36    1    high     56
x5     B      7   24    0     low     31
x6     C      8   27    1     low     35
x7     C     10   33    0  medium     43
x8     B      6   25    0     low     31
x9     c     14   23    1  medium     37

연습문제

문제1의 데이터프레임에서 '합계'와 '평균점수'를 컬럼을 추가 ㄱㄱ


합계 : 국어 + 영어 + 수학

평균 : (국어 + 영어 + 수학) / 3

In [ ]:
df = pd.DataFrame(data = { '국어' : [100, 90, 85, 85, 90, 65, 70, 85],
                           '영어' : [100, 90, 100, 70, 70, 80, 100, 60],
                           '수학' : [90, 90, 75, 95, 90, 75, 90, 75]},
                            columns = ['국어', '영어', '수학'],
                            index = ['홍길동', '김영희', '김희원', '강희진', '최소희', '이사랑', '박아라', '안경진'] )
df

국어   영어  수학
홍길동  100  100  90
김영희   90   90  90
김희원   85  100  75
강희진   85   70  95
최소희   90   70  90
이사랑   65   80  75
박아라   70  100  90
안경진   85   60  75

In [ ]:
df['합계'] = df['국어'] + df['영어'] + df['수학']
df['평균점수'] = (df['국어'] + df['영어'] + df['수학']) / 3
df

국어   영어  수학   합계       평균점수
홍길동  100  100  90  290  96.666667
김영희   90   90  90  270  90.000000
김희원   85  100  75  260  86.666667
강희진   85   70  95  250  83.333333
최소희   90   70  90  250  83.333333
이사랑   65   80  75  220  73.333333
박아라   70  100  90  260  86.666667
안경진   85   60  75  220  73.333333

결측처리

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(data = { 'group' : ['A','B','A','A','B','C','C','B'],
'score' : [10, 9, 10, 20, 7, 8, 10, 6],
'age' : [27, 28, 30, 36, 24, 27, 33, 25]},
columns = ['group', 'score', 'age'],
index = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'] )
df

group  score  age
x1     A     10   27
x2     B      9   28
x3     A     10   30
x4     A     20   36
x5     B      7   24
x6     C      8   27
x7     C     10   33
x8     B      6   25

결측값 처리를 위한 결측값 강제 생성

In [ ]:
df.loc['x1','age'] = np.nan

In [ ]:
df.loc['x3',['score','age']] = np.nan

In [ ]:
df.loc['x8',:] = np.nan
df

group  score   age
x1     A   10.0   NaN
x2     B    9.0  28.0
x3     A    NaN   NaN
x4     A   20.0  36.0
x5     B    7.0  24.0
x6     C    8.0  27.0
x7     C   10.0  33.0
x8   NaN    NaN   NaN

결측값 확인

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, x1 to x8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   group   7 non-null      object 
 1   score   6 non-null      float64
 2   age     5 non-null      float64
dtypes: float64(2), object(1)
memory usage: 556.0+ bytes


In [ ]:
df.isnull() #결측치 True / 아닌것 False

group  score    age
x1  False  False   True
x2  False  False  False
x3  False   True   True
x4  False  False  False
x5  False  False  False
x6  False  False  False
x7  False  False  False
x8   True   True   True

In [ ]:
df.isnull().sum()

group    1
score    2
age      3
dtype: int64

결측값 삭제


데이터명.dropna() : NaN이라고 표기된 값 제거


dropna(how = , axis = )


how : any. all 결측치 처리 방식


any: 목록삭제. NaN이 하나라도 있으면 삭제


all: 단일삭제. 전체가 NaN인 경우 삭제


axis : 0,1 행열 기준



0: 행 기준


1: 열 기준

In [ ]:
# 행(axis=0)을 기준으로 모두 NaN인 행 제거
df.dropna(how = 'all', axis = 0)

group  score   age
x1     A   10.0   NaN
x2     B    9.0  28.0
x3     A    NaN   NaN
x4     A   20.0  36.0
x5     B    7.0  24.0
x6     C    8.0  27.0
x7     C   10.0  33.0

In [ ]:
# 행기준으로 NaN이 하나라도 있는 행을 삭제
df.dropna(how = 'any',axis = 0) # axis = 0 행삭제

group  score   age
x2     B    9.0  28.0
x4     A   20.0  36.0
x5     B    7.0  24.0
x6     C    8.0  27.0
x7     C   10.0  33.0

임계치 삭제


thresh = n : n개 이상 값(결측값이 아닌 값)이 있는 행/열만 선택

In [ ]:
df.dropna(thresh = 2, axis=0)

group  score   age
x1     A   10.0   NaN
x2     B    9.0  28.0
x4     A   20.0  36.0
x5     B    7.0  24.0
x6     C    8.0  27.0
x7     C   10.0  33.0

결측값 대치


fillna(value = ) : NaN에 다른 값을 대입

In [ ]:
df.fillna(value = 0)

group  score   age
x1     A   10.0   0.0
x2     B    9.0  28.0
x3     A    0.0   0.0
x4     A   20.0  36.0
x5     B    7.0  24.0
x6     C    8.0  27.0
x7     C   10.0  33.0
x8     0    0.0   0.0

In [ ]:
df.mean()

<ipython-input-186-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


score    10.666667
age      29.600000
dtype: float64

In [ ]:
df.mode() #최빈값

group  score   age
0     A   10.0  24.0
1   NaN    NaN  27.0
2   NaN    NaN  28.0
3   NaN    NaN  33.0
4   NaN    NaN  36.0

In [ ]:
df.median()

<ipython-input-185-6d467abf240d>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()


score     9.5
age      28.0
dtype: float64

In [ ]:
df.fillna(value = df.mean())

<ipython-input-184-27e1639fa67e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(value = df.mean())


group      score   age
x1     A  10.000000  29.6
x2     B   9.000000  28.0
x3     A  10.666667  29.6
x4     A  20.000000  36.0
x5     B   7.000000  24.0
x6     C   8.000000  27.0
x7     C  10.000000  33.0
x8   NaN  10.666667  29.6

Join (merge함수 사용)

In [ ]:
data_A = {'ID': [1,2,3], 'name': ['Kim', 'Choi', 'Lee']}
df_A = pd.DataFrame(data = data_A, columns = ['ID', 'name'])

data_B = {'ID': [2,3,4], 'age': [33, 15, 20]}
df_B = pd.DataFrame(data = data_B, columns = ['ID', 'age'])

In [ ]:
df_A

ID  name
0   1   Kim
1   2  Choi
2   3   Lee

In [ ]:
df_B

ID  age
0   2   33
1   3   15
2   4   20

pd.merge(데이터프레임1, 데이터프레임2, on = , how =)


*on = 'Key', how= 'inner', 'outer', 'left', 'right'

In [ ]:
df_inner = pd.merge(df_A, df_B, on='ID', how='inner')
df_inner

ID  name  age
0   2  Choi   33
1   3   Lee   15

In [ ]:
df_outer = pd.merge(df_A, df_B, on='ID',how='outer')
df_outer

ID  name   age
0   1   Kim   NaN
1   2  Choi  33.0
2   3   Lee  15.0
3   4   NaN  20.0

In [ ]:
df_left = pd.merge(df_A, df_B, on='ID',how='left')
df_left

ID  name   age
0   1   Kim   NaN
1   2  Choi  33.0
2   3   Lee  15.0

In [ ]:
df_right = pd.merge(df_A, df_B, on='ID',how='right')
df_right

ID  name  age
0   2  Choi   33
1   3   Lee   15
2   4   NaN   20

In [ ]:
df_inner = pd.merge(df_A, df_B) #default: on = 동일한 컬럼명칭,how=inner
df_inner

ID  name  age
0   2  Choi   33
1   3   Lee   15

연습문제

주문정보테이블에 고객정보 테이블을 합쳐라.

단, 주문정보 테이블의 모든 행이 누락되지 않도록 하라.

In [ ]:
# 주문정보
ord_df = pd.DataFrame({'CUST_ID': ['100', '100', '200', '200', '300'],
                       'ORD_NO': ['11', '12', '13', '14', '15'],
                       'ITEM_CD' : ['001', '002', '001', '003', '003']})
# 고객정보
cust_df = pd.DataFrame({'CUST_ID': ['100', '200', '300', '400'],
                        'CUST_NM' : ['KIM', 'LEE', 'PARCK', 'CHOI']})
# 상품정보
item_df = pd.DataFrame({'ITEM_CD': ['001', '003'],
                        'ITEM_NM' : ['Notebook', 'TV']})

In [ ]:
ord_df

CUST_ID ORD_NO ITEM_CD
0     100     11     001
1     100     12     002
2     200     13     001
3     200     14     003
4     300     15     003

In [ ]:
cust_df

CUST_ID CUST_NM
0     100     KIM
1     200     LEE
2     300   PARCK
3     400    CHOI

In [ ]:
df1 = pd.merge(ord_df, cust_df, on='CUST_ID', how='left')
df1

CUST_ID ORD_NO ITEM_CD CUST_NM
0     100     11     001     KIM
1     100     12     002     KIM
2     200     13     001     LEE
3     200     14     003     LEE
4     300     15     003   PARCK